## 2. Data Description

### Data Set 1: Diabetic Patient Hospital Readmission in the US

The current dataset on hospitalized diabetic patient records in the US (1999-2008) is sourced from the following website hosted by the UC Irvine Machine Learning Repository: <https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008>. The dataset was donated to this repository on May 2, 2014 and was originally collected as a Health Facts database of Cerner Corporation (Kansas City, MO ). The present dataset was created from this larger database and published by Strack et al. (2014) in “Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Records” in the journal of BioMed Research International.

The raw data set contains 101,766 observations, each representing a single diabetic patient at one of 130 US hospitals between 1999-2008. Each patient received medications and laboratory treatment and stayed at the hospital for up to 14 days. 51 variables are recorded for each patient regarding their identity (e.g. race, age, gender), the hospice treatment they received, and the days that elapsed before inpatient readmission.

The original goal of the dataset was to predict the early readmission of a diabetic patient within 30 days of discharge based on various therapeutic and preventative hospital interventions. This research would provide more information on the state of diabetes care in US hospitals and the impact of certain treatments on patient outcomes.

To download the dataset, click on the top blue box labeled "download" on the linked webpage. The dataset used in this document was downloaded on February 22, 2026.

The original dataset contained multiple hospital records of the same patient, interfering with the independence of the observations. To satisfy this assumption for future statistical analyses, we removed all patients with duplicate records (30,248 observations), leaving us with 71,518 independent observations. Non-predictor identifier variables (`encounter_id`, `patient_nbr`, etc) were removed, as well as variables missing the majority of their values (`weight`, `payer_code`, `medical_speciality`). Finally, I removed `diag_1`, `diag_2`, and `diag_3` which corresponded to the primary and secondary diagnoses that patients received. There are up to 923 different diagnoses the patient could have received, which is too granular for this analysis.

This filtering leaves variables for demographics (race, gender, age), type of hospital admission (e.g. emergency), time spent in hospital, the number of procedures patients received, whether any of 23 of different drugs were prescribed, and more. Though thoroughly analyzing all 23 drugs is beyond the scope of this analysis, this report will complete some basic preliminary analyses to determine which of the drugs to investigate further.

To prepare for logistic regression analyses of the data, we converted two categorical variables (`max_glu_serum`: measurement of glucose in blood serum; and `a1cresult`: measurement of hemoglobin A1c) into binary variables, where 1 indicates that a certain test was performed and 0 indicates that it was not taken. We similarly converted the `readmitted` variable to be binary, indicating whether a patient was readmitted within 30 days of their discharge or not.

### Data Set 2: Indicators of Heart Disease (2022)

The current data set on crucial indicators for heart disease from patients in the United States (2022) is sourced from the following website hosted by Kaggle: <https://www.kaggle.com/datasets/kamilpytlak/personal-key-indicators-of-heart-disease>. The data set originally comes from the Centers for Disease Control and Prevention (CDC) and is a part of the Behavioral Risk Factor Surveillance System (BRFSS). It was originally collected by the CDC and BRFSS to gather data on the health status of U.S. residents across all 50 states, the Distirct of Columbia, and 3 U.S. territories. To download the dataset, scroll to the end of the "About Dataset" section and click the download icon (an arrow pointing down). The dataset was downloaded on February 22, 2026.

The raw data set contains 319795 observations, each representing an individual surveyed through the BRFSS in 2022. Each individual answered a series of questions regardin their health. Eighteen variables were recorded for each individual, including identity characteristics (e.g., sex and race) and indicators of overall cardiovascular health, such as BMI, smoking status, mental health, and diabetes status.

The original purpose of the dataset was to monitor the population health and identify crucial risk factors for diseases such as heart disease to inform public health policy and prevention efforts. This research builds on that goal by providing further insight into how these risk factors contribute to the prediction of heart disease and overall cardiovascular health outcomes.

The data set was cleaned by addressing implausible values in numeric variables, specifically `bmi` and `sleep_time`. In the `bmi` variable, extremely low values were observed (minimum = 12.02) that are considered physiologically implausible; these values were treated as NA. Similarly, the `sleep_time` variable included extreme values (minimum = 1 hour and maximum = 24 hours). While achieving such durations are technically possible, they are highly unusual and could disproportionately influence subsequent analyses, so they were also recorded as NA to improve data quality and reliability.
