---
title: "Predicting Heart Disease and BMI"
authors: "Katelynne De Lara & Lily von Behren"
format: 
  pdf:
    documentclass: article
    number-sections: true
    geometry:
      - top=20mm
      - left=25mm
      - right=25mm
      - heightrounded
execute: 
  message: false
  warning: false
  echo: false
bibliography: ../bibliography/references.bib
engine: knitr
---

\begin{abstract}

Resulting from diverse biological, behavioral, and demographic factors, cardiovascular disease is the foremost cause of mortality in the United States, with Body Mass Index (BMI) serving as a useful but imperfect indicator of underlying health and risk patterns. This study examines how race, sex, age, pre-existing health conditions, and behavior (such as smoking and alcohol consumption) relate to BMI and the probability of experiencing a heart attack. Multiple linear regression was performed to investigate the factors involved in BMI, while a logistic regression model was fit to determine how predictors impacted the odds of heart disease. The final predictors used for both models were determined via exhaustive, forward, and backward model selection to optimize the Bayesian Information Criterion (BIC). Through the multiple linear regression, we found that physical activity and general health were the strongest predictors of BMI, with individuals who engaged in physical activity having lower BMI and those reporting poorer health having higher BMI (p < 0.05). Interestingly, smoking and age were also significantly associated with lower BMI (p < 0.05), though their effects were smaller in magnitude. The logistic regression model revealed that individuals with the greatest odds of experiencing heart disease were over 34 years old, White, and female. Medical conditions such as stroke, kidney disease, diabetes, skin cancer, asthma, and difficulty walking also significantly (p < 0.05) increased the risk of heart attack. On the other hand, this risk significantly (p < 0.05) decreased for those with good health and, unexpectedly, those who consumed alcohol. However, these findings are subject to limitations related to the use of self-reported data and the exclusion of potentially relevant and environmental factors. Future work may extend this analysis by incorporating additional predictors and longitudinal data to better capture variation in BMI and heart disease risk.

\end{abstract}

{{< include 1-introduction.qmd >}}


{{< include 2-data-methods.qmd >}}

{{< pagebreak >}}

{{< include 3-results.qmd >}}

{{< pagebreak >}}

{{< include 4-discussion.qmd >}}



\newpage 

## Bibliography {-}
::: {#refs}
:::

\newpage 

{{< include 5-appendix.qmd >}}

<!-- This section should not be edited by hand. If you add bibliographic sources to bibliography/references.bib and then cite them in your report using @... then the citations will be automatically printed here. -->

<!-- This section does not count towards your page limit -->
