## Appendix


<!-- MLR MODEL SELECTION -->
::::: {layout="[0.25, 0.75]"}
:::{#table}
```{r}
#| echo: false
#| label: tbl-selected-vars-mlr
#| tbl-cap: "Selected Predictors Based on BIC (for exhaustive, forward, and backward selection technqiues)"

selected_mlr_vars |> kable()
```
:::
:::{#plots}
```{r}
#| echo: false
#| fig-cap: "A) Multiple Linear Regression on Log(BMI): Exhaustive Model Selection"

# Exhaustive
plot(best_mlr_all_sub, scale = "bic")

```

```{r}
#| echo: false
#| fig-cap: "B) Multiple Linear Regression on Log(BMI): Forward Model Selection"
#| # Forward
plot(best_mlr_fwd, scale = "bic")

```

```{r}
#| echo: false
#| fig-cap: "C) Multiple Linear Regression on Log(BMI): Backward Model Selection"
# Backward
plot(best_mlr_bwd, scale = "bic")
```
:::
::::


<!-- ASSUMPTIONS FOR MLR -->


::::: {layout="[0.45, 0.45]"}
<div>

```{r}
#| echo: false
#| label: fig-mlr-resfit

plot(final_mlr, which = 1)
```

</div>

<div>

```{r}
#| echo: false
#| label: fig-mlr-qq

plot(final_mlr, which = 2)
```

</div>
:::::

```{r}
#| echo: false
#| label: fig-mlr-leverage
#| fig-align: "center"
#| fig-width: 5
#| fig-height: 3

plot(final_mlr, which = 4)
```


<!-- LOGISTIC REGRESSION MODEL SELECTION -->

::::: {layout="[0.45, 0.45]"}
::: column
```{r}
#| echo: false
#| label: fig-heartdisease-bmi-hist
## BODY MASS INDEX (BMI)

ggplot(data = disease_data, aes(x = bmi, fill = factor(heart_disease))) +
  geom_density(alpha = 0.5, color = "black") + 
  labs(x = "BMI",
       y = "Count",
       fill = "Heart Disease") +
  scale_fill_manual(
    values = c("0" = "skyblue", "1" = "tomato"),
    labels = c("No", "Yes")
  ) +
  theme_classic() +
  theme(legend.position = "bottom")

```

```{r}
#| include: false

# BMI
ggplot(data = disease_data, aes(y = bmi, x = factor(heart_disease), 
                            fill = factor(heart_disease))) +
  geom_boxplot() + 
  labs(x = "Heart Disease", y = "BMI") + 
  scale_x_discrete(labels = c("0" = "No Heart Disease",
                              "1" = "Heart Disease")) +
  scale_fill_manual(
    values = c("0" = "skyblue", "1" = "tomato"),
    labels = c("No", "Yes")
  ) +
  theme_classic() +
  theme(legend.position = "none")
```
:::

::: column
```{r}
#| echo: false
#| label: fig-heartdisease-bmi-bar

disease2 <- disease_data |>
  mutate(sleep_time = case_when(
    sleep_time <= 10 & sleep_time >= 7 ~ "Healthy Sleep (7-10 hrs)",
    sleep_time < 7 ~ "Sleep Deprived (<7 hrs)",
    sleep_time > 10 ~ "Extra Sleep (>10 hrs)",
    TRUE ~ NA_character_),
    
    bmi = case_when(
    bmi < 19 ~ "Underweight",
    bmi >= 19 & bmi < 25 ~ "Normal Weight",
    bmi >= 25 & bmi < 30 ~ "Overweight",
    bmi >= 30 ~ "Obese",
    TRUE ~ NA_character_),
    
   # age_category = case_when(
 #   age_category %in% young ~ "Young (18-39)",
  #  age_category %in% middle_age ~ "Middle Aged (40-59)",
  #  age_category %in% old ~ "Elderly (60-80+)",
  #  TRUE ~ NA_character_)
    
    )

# BMI
ggplot(data = disease2, aes(x = factor(heart_disease), fill = bmi)) +
  geom_bar(color = "black", position = "fill") + 
  labs(x = "Heart Disease",
       y = "Count",
       fill = "BMI") +
  scale_x_discrete(labels = c("0" = "No Heart Disease",
                              "1" = "Heart Disease")) +
  theme_classic() + 
  theme(legend.position = "bottom")
```
:::
:::::

```{r}
#| include: false

# BMI
ggplot(data = disease_data, aes(y = bmi, x = factor(heart_disease), 
                            fill = factor(heart_disease))) +
  geom_boxplot() + 
  labs(x = "Heart Disease", y = "BMI") + 
  scale_x_discrete(labels = c("0" = "No Heart Disease",
                              "1" = "Heart Disease")) +
  scale_fill_manual(
    values = c("0" = "skyblue", "1" = "tomato"),
    labels = c("No", "Yes")
  ) +
  theme_classic() +
  theme(legend.position = "none")

```

::: {layout="[0.3, 0.3, 0.3]"}
```{r}
#| include: false

# PHYSICAL ACTIVITY
ggplot(data = disease_data, aes(x = factor(heart_disease), fill = factor(physical_activity))) +
  geom_bar(color = "black", position = "fill") + 
  labs(x = "Heart Disease Status",
       y = "Count",
       fill = "Physically Active") +
  scale_x_discrete(labels = c("0" = "No Heart Disease",
                              "1" = "Heart Disease")) +
  scale_fill_manual(
    values = c("0" = "skyblue", "1" = "tomato"),
    labels = c("No", "Yes")
  ) +
  theme_classic() + 
  theme(legend.position = "bottom")
```

```{r}
#| include: false
## BEHAVIOR

# SLEEP
ggplot(data = disease2, aes(x = factor(heart_disease), fill = sleep_time)) +
  geom_bar(color = "black", position = "fill") + 
  labs(x = "Heart Disease",
       y = "Count",
       fill = "Sleep") +
  scale_x_discrete(labels = c("0" = "No Heart Disease",
                              "1" = "Heart Disease")) +
  theme_classic() + 
  theme(legend.position = "bottom")
```

</div>
:::


::::: {layout="[0.25, 0.75]"}
:::{#table}
```{r}
#| echo: false
#| label: tbl-selected-vars-log-reg
#| tbl-cap: "Selected Predictors Based on BIC (for exhaustive, forward, and backward selection technqiues)"

selected_vars |> kable()
```
:::
:::{#plots}
```{r}
#| echo: false
#| fig-cap: "A) Logistic Regression for Log-Odds of Heart Disease: Exhaustive Model Selection"

# Exhaustive
plot(best_log_reg_all_sub, scale = "bic")

```

```{r}
#| echo: false
#| fig-cap: "B) Logistic Regression for Log-Odds of Heart Disease: Forward Model Selection"
#| # Forward
plot(best_log_reg_fwd, scale = "bic")

```

```{r}
#| echo: false
#| fig-cap: "C) Logistic Regression for Log-Odds of Heart Disease: Backward Model Selection"
# Backward
plot(best_log_reg_bwd, scale = "bic")
```
:::
::::


<!-- ASSUMPTIONS FOR LOGISTIC REGRESSION -->


```{r}
#| echo: false
#| label: fig-log-odds-mental-health
#| fig-cap: "Logistic Regression Linearity Assumption Validation. Every distinct value of mental health constituted a new group, in which the average log-odds was calculated. The blue line represents a least squares line."

## EVALUTION OF LINEARITY OF MENTAL HEALTH vs LOG ODDS -- using training data

#heart_train %>% 
#  ggplot() +
#  aes(x = mental_health) +
#  geom_histogram(na.rm = TRUE, fill = "skyblue", color = "black") +
#  theme_classic()

emplogitplot1(heart_disease ~ mental_health,
              data = heart_train,
              ngroups = "all",
              out = TRUE)

```


```{r}
#| echo: false
#| label: tbl-outliers
#| tbl-cap: "Outliers in Heart Disease Dataset. Outliers had abnormally large Pearson residuals and Cook's distance for the logistic regression for the log-odds of heart disease."

# identifying outliers
heart_train[c(115488,65997,96834, 52951, 160975,222531), ] |> kable() |>
  kable_styling() |>
  row_spec(0, angle = 90) |>
  column_spec(which(names(heart_train) == "race"), width = "3em")



```

```{r}
#| include: false

# remove outliers & refit the regression
heart_train_no_outliers <- heart_train[-c(115488,65997,96834, 52951, 160975,222531), ]


log_reg_no_outliers <- glm(
  heart_disease ~  smoking + alcohol_drinking + stroke + diff_walking + sex + age_category + race + diabetic + gen_health + asthma + kidney_disease + skin_cancer,
  data = heart_train_no_outliers,
  family = "binomial"
)


summary(log_reg_no_outliers)

```

::::: {layout="[0.45, 0.45]"}
:::{#plot1}
```{r}
#| echo: false
#| label: fig-resids-fitted-log-reg

# Residuals vs Fitted
plot(final_log_reg, which = 1)

```
:::
:::{#plot2}
```{r}
#| echo: false
#| label: fig-cooks-log-reg
# Cook's distance
plot(final_log_reg, which = 4)
```
:::
:::::




::::: {layout="[0.45, 0.45]"}
<div>

```{r}
#| include: false

# Scale Location
plot(final_log_reg, which = 3)
```

</div>

<div>

```{r}
#| include: false

# Q-Q residuals
plot(final_log_reg, which = 2)
```

</div>
:::::

```{r}
#| echo: false
#| label: fig-binned-resids-log-reg
#| fig-width: 4
#| fig-height: 3.5

library(arm)
binnedplot(fitted(final_log_reg), 
           residuals(final_log_reg, type = "response"), 
           nclass = NULL, 
           xlab = "Expected Values", 
           ylab = "Average residual", 
           main = "Binned residual plot", 
           cex.main = 0.9,
           cex.pts = 0.8, 
           col.pts = 1, 
           col.int = "gray")

```



<!-- MODEL COEFFICIENT TABLES -->
```{r}
#| echo: false
#| label: tbl-mlr-reg
#| tbl-cap: "Multiple Linear Regression Model Coefficients. "

mlr_table %>%
  kable(col.names = c(
    "Coefficient",
    "Estimate",
    "Std. Error",
    "t value",
    "p-value",
    "Lower CI",
    "Upper CI"
  ))

## Coefficients represent approximate percentage changes in BMI

```


```{r}
#| echo: false
#| label: tbl-log-reg-coeffs
#| tbl-cap: "Logistic Regression Model Coefficients. Red rows indicate coefficients that increase the odds of heart disease. Green rows indicate coefficients that decrease the odds of heart disease. Gray rows indicate coefficients with insignificant p-values."

reg_sum <- summary(final_log_reg)

coefficients <- as.data.frame(reg_sum$coefficients)
coeff_sorted <- coefficients[order(coefficients$Estimate, decreasing = TRUE), ]


# calculate the odds & probability
coeff_sorted <- coeff_sorted |>
  mutate(
    odds_coeff = exp(coeff_sorted$Estimate),
    #prob = odds_coeff / (1 + odds_coeff),
    ci_low = exp(Estimate - 2*`Std. Error`),
    ci_high = exp(Estimate + 2*`Std. Error`)
  )

colnames(coeff_sorted) <- c("Estimate (log-odds)", "Std. Error", "Z value", "P-value", "Estimate (odds)",  "CI low (odds)", "CI high (odds)")

coeff_sorted |> kable() |>
  kable_styling(full_width = FALSE) |>
  column_spec(1:ncol(coeff_sorted), width = "4em") |>
  row_spec(which(coeff_sorted$`Estimate (log-odds)` >= 0),  background = "#ffe6e6") |>
  row_spec(which(coeff_sorted$`Estimate (log-odds)` < 0), background = "#e6ffe6") |>
  row_spec(which(coeff_sorted$`P-value` > 0.05), background = "#c7d1d9")
```

